hazelcast:
  image: hazelcast/hazelcast:3.8.6
  restart: always
  container_name: hazelcast-{{ ENV }}
  net: host
  privileged: true
  environment:
    - TZ=Asia/Shanghai
    - JAVA_OPTS=-XX:+ExitOnOutOfMemoryError -Xms4G -Xmx8G
  volumes:
    - ./hazelcast.xml:/opt/hazelcast/hazelcast.xml
