redis:
  image: redis:4 
  container_name: redis-{{ ENV }}
  restart: always
  net: host
  privileged: true
  environment:
    - TZ=Asia/Shanghai
  ulimits:
    memlock:
      soft: -1
      hard: -1
  volumes:
    - ./data:/data
    - ./redis.conf:/etc/redis.conf
  command:
    redis-server /etc/redis.conf

redis-sentinel:
  image: redis:4
  container_name: redis-sentinel
  restart: always  
  net: host
  environment:
    - TZ=Asia/Shanghai
  volumes:
    - ./sentinel-data:/data/sentinel
    - ./sentinel.conf:/etc/sentinel.conf
  command:
    redis-sentinel /etc/sentinel.conf
