- name: 创建存储数据文件夹
  file: path=/data/elasticsearch-{{ ENV }} state=directory  owner={{ DOCKER_USER }}

- name: 复制Elasitcsearch插件
  copy: src=../files/plugins dest=/data/elasticsearch-{{ ENV }}

- name: 生成docker-compose文件,JAVA内存为物理总内存一半
  template:  src=docker-compose.yaml dest=/data/elasticsearch-{{ ENV }}

- name: 启动服务
  shell: "cd /data/elasticsearch-{{ ENV }} \ 
         && docker-compose down \
         && docker-compose up -d"
